### ISSUE TITLE
Load data Local infile forbidden 

### ISSUE THREAD

**Issue by themattnicholson** [webyog/sqlyog-community#2265] opened 2020-10-12 18:00 UTC
Problem still exists in latest version.
V13.1.7 64 Bit. 
 
<img width="747" alt="Screenshot 2020-10-12 at 19 58 08" src="https://user-images.githubusercontent.com/20444949/95776841-622ae100-0cc5-11eb-8a75-34b2fe503998.png">

**Comment by sibwy** [comment] 2020-10-13 08:50
Please confirm if you are referring to the issue recorded, [here](https://github.com/webyog/sqlyog-community/issues/2240).

**Comment by themattnicholson** [comment] 2020-10-13 09:09
> Please confirm if you are referring to the issue recorded, [here](https://github.com/webyog/sqlyog-community/issues/2240).

Very similar. However, i am unable to get it to successfully work at all. Opening new connection and running command in query window returns Error 2000 like current. 

Going via the menu tree it does work.

**Comment by sibwy** [comment] 2020-10-15 05:27
Duplicate of the issue [#2240](https://github.com/webyog/sqlyog-community/issues/2240)

**Closed** 2020-10-15 05:27 UTC

**Comment by wl-sqlyog** [comment] 2021-02-19 09:59
Is there any update/solution on this issue ? I have checked that this problem cames up with SQLYog 13.1.3 and still in 13.1.7. Release 13.1.2 was the last version where LOAD DATA LOCAL INFILE succeeded. 
Mentioned bypass/workaround with opening new connection does not help. Doing load via GUI is no valid solution because we have a lot of scripts to do work.

**Comment by illfated** [comment] 2021-02-19 22:10
@wl-sqlyog : Please follow issue ticket #2240 for information, future updates and solutions.
