### ISSUE TITLE
0xOD is additionally attached at every end of lines.

### ISSUE THREAD

**Issue by gloomyrose** [webyog/sqlyog-community#2128] opened 2017-01-16 08:23 UTC
Hello! I'm using SQLyog, and has found a strange phenomenon. The following explains how I make the phenomenon happen.

1. I edited a stored procedure with using Query Editor after clicking 'Alter Stored Procedure...'.
2. I updated the stored procedure with pressing 'F9' just after selecting all sentences.
3. After right-clicking the DB object, I clicked 'Backup/Export' and the dump file has been created.
4. The stored procedure has '0x0D0D0A' as line-breaking string at every end of lines, but the other stored procedures that I has never touched have '0X0D0A' as line-breaking string.

My partner, who is using MySQL Workbench, sometimes edits stored procedures. and whenever I compare his stored procedures and mine with a diff tool, it says additional lines have been found. It's so annoying.

Could you fix this problem? And if it's not a problem, how could I do workaround for this?

**Comment by wyaadarsh** [comment] 2017-01-20 10:22
Hello,

We have fixed this issue. Can you please create a support ticket by mailing at support@webyog.com so we can share the links to download the latest build with the fix which can not be provided in an open forum.

**Comment by gloomyrose** [comment] 2017-01-20 14:18
Ah, I'm so happy to hear that the problem has been fixed! I could mail you and get the link for the latest build, but I'll wait for the build which can be downloaded from the homepage.

Thank you so much!

**Comment by wyaadarsh** [comment] 2017-01-23 06:51
We just wanted to be sure that the issue is fixed. Hence, it will be of great  help if you could create a support ticket and we could provide a private build to confirm the fix.

**Comment by wyaadarsh** [comment] 2017-10-05 06:13
Fixed in SQLyog 12.4.1

**Closed by wyaadarsh** 2017-10-05 06:13 UTC
