### ISSUE TITLE
convert BLOB to HEX is broken for binary fields

### ISSUE THREAD

**Issue by fritzmg** [webyog/sqlyog-community#2145] opened 2017-10-26 09:44 UTC
I noticed this major problem in SQLyog Community Edition 12.4.3 (64 bit):

1. Create a test database and import the following SQL: [test_mysqldump.zip](https://github.com/webyog/sqlyog-community/files/1417736/test_mysqldump.zip)
2. Run this query once: https://gist.github.com/IcyMidnight/159151 (to create the `uuid_from_bin` function).
3. Run `SELECT uuid_from_bin(uuid) FROM test;` - the result will be `E1CB40DD-70FB-11E7-979D-F08FF9320FB4`.
4. Run _Backup Database As SQL Dump... (Ctrl+Alt+E)_ - make sure to enable __Convert BLOB to HEX__.
5. Re-import that dump into a new or truncated database.
6. Run `SELECT uuid_from_bin(uuid) FROM test;` again - the result will be `FFFFFFE1-FFFF-FFCB-40FF-FFFFDD70FFFF`

This is the insert created by `mysqldump` with the `--hex-blob` option:
```sql
INSERT INTO `test` VALUES (0xE1CB40DD70FB11E7979DF08FF9320FB4);
```

This is the insert created by SQLyog with the __Convert BLOB to HEX__ option:
```sql
insert  into `test`(`uuid`) values 
(0xffffffe1ffffffcb40ffffffdd70fffffffb11ffffffe7ffffff97ffffff9dfffffff0ffffff8ffffffff9320fffffffb4);
```
For some reason SQLyog seems to add "padding" with `ffffff`. This makes SQL dumps by SQLyog that contain binary fields completely unusable. I hope this is fixed soon since we work primarily with Contao which relies on binary stored UUIDs (see [here](https://github.com/contao/core-bundle/blob/4.4.7/src/Resources/contao/dca/tl_files.php#L147)). Currently I cannot use dumps from SQLyog because of this issue.

_Note:_ this problem does __not__ occur when using _Copy Database To Different Host/Database..._. There the binary data is transferred correctly.

**Comment by fritzmg** [comment] 2017-10-26 10:10
Btw. there is another related error: when using the __Convert BLOB to HEX__ option, SQLyog creates the following insert for binary fields that are empty:
```sql
insert  into `test`(`uuid`) values 
(0x);
```
This will lead to the following SQL error:
```
Error Code: 1054 - Unknown column '0x' in 'field list'
```

**Comment by peterwy** [comment] 2017-10-26 10:12
We are checking.

**Comment by sibwy** [comment] 2017-10-26 10:29
Thanks for reporting this issue. We can reproduce it at our end.
We will debug the issue and update once we have the fix.

**Comment by fritzmg** [comment] 2017-11-27 15:42
This problem is still present in `12.5.0`.

**Comment by sibwy** [comment] 2017-11-27 17:02
The fix for this issue is scheduled for the coming release. 

For further discussion, please use our support email [support@webyog.com](mailto: support@webyog.com)

**Comment by sibwy** [comment] 2018-01-15 16:04
This issue is fixed in SQLyog 12.5.1.

**Closed by sibwy** 2018-01-15 16:04 UTC

**Comment by iibasarah** [comment] 2019-07-04 20:35
I backup database without enabling Convert BLOB to HEX for image field. After restoring SQL dump all my image is broken. How to fix it. it's a lot of image data to fix.

**Comment by fritzmg** [comment] 2019-07-05 06:42
I think that's rather difficult to fix and I don't think there are any ready made solutions.

**Comment by peterwy** [comment] 2019-07-05 08:40
It is only safe to convert binary data  (BLOB, BINARY and VARBINARY data types) to HEX when dumping.  The reason is that the dump-file generated is UTF8-encoded and since not any byte-sequence is valid UTF8 and binary data may contain any byte sequence, data loss may occur. The option to convert to HEX was introduced for exactly that reason. 

It is not a bug with SQLyog but an issue with the encoding.
